### ISSUE TITLE
cannot import name 'SCOPES' from 'core.config'

### ISSUE THREAD

**Issue by spoetnik** [bergran/fast-api-project-template#2]
Error on clean install...

`  File "./main.py", line 6, in <module>
    from core import urls
  File "./core/urls.py", line 8, in <module>
    from apps.oauth2.urls import router as router_oauth2
  File "./apps/oauth2/urls.py", line 4, in <module>
    from apps.oauth2.views.token_access import router as router_token_access
  File "./apps/oauth2/views/token_access.py", line 12, in <module>
    from core.config import SCOPES
ImportError: cannot import name 'SCOPES' from 'core.config' (./core/config.py)`

**Comment by bergran** [comment]
Thanks for reporting and it fixed today on tag 0.1.2
